tools/actions/initializer.py

Seems this was forgotten in f9de8c4283ffa11c0382eff5952422f0bb64159a

tools: Remove unused requests import

---

tools/services/user_manager.py

fixes #109
**NOTE:** not tested

user_manager.py: use one variable for apps dir

---

tools/actions/session_manager.py

https://stackoverflow.com/questions/303200/how-do-i-remove-delete-a-folder-that-is-not-empty

session: don't panic when removing old userdata if its not empty

---

tools/helpers/http.py

while downloading, progress bar shows file sizes in bytes. it prints large numbers and makes it harder to understand the info.
this commit-
1.) shows file sizes in megabytes and an approximate download speed along with it. hoping it would make the download information easier to understand.
2.) adds "daemon=True", in the thread which starts progress(). it kills the progress thread if download thread is killed by ctrl+c. previously one had to press ctrl+c twice, one to kill downloading and one to kill progress bar thread.

tweak tools.helpers.http.download()

---

tools/__init__.py
tools/actions/app_manager.py
tools/helpers/arguments.py
tools/interfaces/IPlatform.py

Launch intent

---

tools/actions/container_manager.py
tools/helpers/drivers.py

Improve robustness of the dynamic aidl version picker

---

tools/helpers/__init__.py
tools/helpers/gpu.py
tools/helpers/lxc.py

Try to choose a supported gpu on PRIME devices

Default nvidia to swiftshader

---

data/Waydroid.desktop
debian/control
debian/waydroid.install
polkit/org.waydro.id.policy
tools/__init__.py
tools/actions/initializer.py
tools/helpers/arguments.py

Add a graphical init to be run as root, which we can use in
first-launch through pkexec

Add first-launch command

---

.abstruse.yml

Please merge
- https://github.com/waydroid/libglibutil/pull/2
- https://github.com/waydroid/libgbinder/pull/2
- https://github.com/waydroid/gbinder-python/pull/3
before merging this one.

CI: add support for rolling releases

---

Makefile
debian/rules

Fixes: https://github.com/waydroid/waydroid/issues/491
Fixes: https://github.com/waydroid/waydroid/issues/489

Fix debian service not autostarting

---

tools/helpers/gpu.py
tools/helpers/lxc.py

Attempts to set the correct ro.hardware.vulkan value based on the
loaded drm driver name

Add mainline vulkan support

---

tools/helpers/gpu.py
tools/helpers/lxc.py

Necessary for minigbm_gbm_mesa

gpu: Also mount card node

---

data/scripts/waydroid-net.sh

Use `command -v` instead of `which`

---

data/configs/config_base
tools/actions/container_manager.py
tools/helpers/lxc.py

lxc: Create session-specific mount entries

---

tools/helpers/lxc.py

close https://github.com/waydroid/waydroid/issues/793

Add missing environment variable BOOTCLASSPATH to waydroid shell

---

CODE_OF_CONDUCT.md

Added **Code Of Conduct** for this open source project to make it _better_ in terms of **community standards**.
**Code Of Conduct** in a project makes it more community driven which is what open-source aims at. So, I hope adding this would add a value to the project by increasing its community standards.

Added Code Of Conduct

---

systemd/waydroid-container.service
waydroid.py

Ensure default umask to avoid surprises with file permissions.

---

tools/actions/container_manager.py
tools/helpers/lxc.py

lxc: Mount DMA-BUF Heaps

---

tools/helpers/arch.py

More and more modern AArch64 SoCs present both in computers and phones can no longer run normal arm64 image builds which (currently anyway) also ship various amounts of 32-bit executables that cannot be natively executed; thus let's target an upcoming `arm64_only` OTA channel instead:
```
x1e-vivobook:~$ doas waydroid init
[16:51:34] AArch64 CPU does not appear to support AArch32, assuming arm64_only...
[16:51:34] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_arm64_only/VANILLA.json, error: 404
...
```
I've also verified this can accurately detect 32-bit support on Android kernels as old as v4.4 (Halium 9) which has more or less been the minimum viable target for Waydroid since the beginning, should work on things even older too though.
Perhaps …

arch: Separately identify arm64_only CPUs without AArch32 support

---

tools/actions/container_manager.py
tools/actions/session_manager.py
tools/actions/status.py
tools/actions/upgrader.py
tools/config/save.py
tools/helpers/lxc.py
tools/helpers/props.py

> [!WARNING]  
> I didn't actually test the changes, so a test/review would be very much appreciated and required before a potential merge.
remove some unused python imports to reduce memory usage slightly

Remove unused python imports
