scripts/install.sh

Install script didn't work for me because I'm using `fish` as my shell, this fixed the issue.

use `sudo bash` instead of `sudo -s`

---

tools/config/__init__.py

There should be nothing in `/home` other than user home directories. `.waydroid` is not a user home directory, so shouldn't be there.
The right location for system services to write and read data from is `/var/lib/<application name>`. Waydroid is (partially) a system service, so it should write it's stuff there. As far as I understand Ubuntu Touch has various directories in `/var/lib` writeable, and if they want Waydroid they should make `/var/lib/waydroid` writeable too.
This way Waydroid works like it should on _all_ distros and it isn't weird everywhere just because of Ubuntu Touch :stuck_out_tongue_winking_eye:

Store data in /var/lib/waydroid rather than /home/.waydroid

---

debian/control

Otherwise an error appears:
`[14:49:51] Extracting to /var/lib/waydroid/images
[14:49:54] ERROR: LXC is not installed
[14:49:54] See also: <https://github.com/waydroid>`

debian: Add LXC as dependency

---

tools/actions/upgrader.py

Currently if a user have a custom image (like from aur) and runs waydroid upgrade he will get no output and think that there is no new version.
This pr add a friendly message to inform him.

upgrade: log that no we will not upgrade if a preinstalled image exists

---

tools/helpers/lxc.py

There is no guarantee that `PATH` ends with a colon, so we need to add one between the old `$PATH` and the parts we want to append.

lxc: do prepend colon to Android PATHs in shell

---

data/scripts/waydroid-net.sh

Ran into some issue with this on NixOS. This should avoid any problems in the future. Only creates the misc folder, as `varlib` should exists already.

scripts: make sure misc subfolder exists

---

tools/config/load.py
tools/helpers/lxc.py

On some platforms, like a VM, we don't have the "getprop" android
utility available. It could be, also, that the default values
for some properties don't match the target device.
With this PR, one can add a [properties] section in waydroid.cfg,
that will act as an override for the values put by waydroid.
Example, on our LuneOS x86 VM:
[properties]
ro.hardware.gralloc=default
ro.hardware.egl=mesa
A minimal waydroid.cfg could even be shipped with waydroid, and
the rest of the configuration will be filled with "waydroid init".
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>

Add an optional [properties] in waydroid.cfg

---

FUNDING.yml

You might need to enable it in the project's _Settings_ as well. See [official documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository).
Fixes #17

Add sponsor button

---

tools/actions/initializer.py

Don't try to fetch from an URL with a space inside.

tools: Fix device names with spaces in initializer

---

tools/helpers/lxc.py

Providing access to the hosts `/dev/net/tun` is required by at
least some VPN clients, for example F5 Access.

Mount TUN device for use by Android VPNs.

---

debian/waydroid-container.service
tools/__init__.py
tools/actions/initializer.py
tools/helpers/__init__.py
tools/helpers/arguments.py
tools/helpers/ipc.py

In the interest of simplifying the installation of waydroid, make it possible to start the container manager before running init.
The intended usecase is to have waydroid-container automatically enabled and started on install. This was previously impossible because the service would immediatly stop because waydroid was not initialized.

Wait for init

---

data/configs/config_1
data/configs/config_2

doing this will allows LXC to create their own PTY instead of mounting host, this should be more secure then mounting /dev/pty 
addresses 
#145 #238

Allows waydroid to create PTY

---

data/waydroid.market.desktop
debian/waydroid.links

When clicking market:// protocol on Linux distro host, then open it on Waydroid.
Related: https://github.com/waydroid/waydroid/issues/412

Add Android Market Protocol Handler

---

tools/helpers/lxc.py

- Devices with libnfc-nci might have their NFC HAL crash when
the config doesn't exist or contains invalid data. Fix it.
Fixes NFC HAL crashing on UT on the Pixel 3a.

lxc: Optionally bind-mount NFC config

---

tools/actions/initializer.py

When changing system_type, for example.
Timestamps only make sense when compared to the same ota channel.
Fixes: #435

init: Always redownload the image when changing parameters

---

README.md

The old room address no longer works. Use new one as listed in waydro.id

Update Matrix link

---

tools/actions/container_manager.py
tools/actions/upgrader.py
tools/helpers/__init__.py
tools/helpers/protocol.py
tools/services/clipboard_manager.py
tools/services/hardware_manager.py
tools/services/user_manager.py

When restarting the lxc container our binder services will receive a
binder_presence event and will try to re-register on the service manager.
If the service manager was created with aidl2 and the new android version
uses aidl3 this will fail with:
Failed to add service waydroidusermonitor: -2147483647
When that happens, try to restart the service by getting a new service
manager that can handle the new aidl protocol version.

Support upgrading major android versions

---

Makefile

```
❯ sudo pacman -U --noconfirm waydroid-git-1.2.1.r32.g*-1-any.pkg.tar.zst
...
error: failed to commit transaction (conflicting files)
waydroid-git: /lib exists in filesystem (owned by filesystem)
waydroid-git: /lib/systemd/system/waydroid-container.service exists in filesystem
Errors occurred, no packages were upgraded.
```
We can't install that file under `/lib` because it just a symbolic link.
```
❯ file /lib
/lib: symbolic link to usr/lib
```
Note: Distro: Arch Linux

Makefile: Add prefix for systemd directory

---

tools/helpers/arguments.py

There is a typo in help text of stop session command. "start session" should be "stop session".

fix typo in arguments.py

---

data/configs/config_2

Hello everyone! I propose enabling the "No New Privileges" restriction for the container. 
"No New Privileges" is a restrictive flag on a process that prevents changing the effective UID, GID or capability set during an **execve**. It also restricts MAC domain transition, and allows a process to enable seccomp and Landlock self-restriction without CAP_SYS_ADMIN.
**Possible benefits**:
* Preventing unwanted AppArmor domain transition
* Preventing SUID flag and other "privileged file" flag based security risks.
**Possible problems**:
* I don't know how NNP affects SELinux domain transitions. AppArmor has a guaranteed restrictive domain transition feature (profile stacking) that works with NNP enabled, but I don't know whether the same exists in SELinux.
* I don't know how …

Enable the "No New Privileges" restriction for the container

---

data/configs/config_1
data/configs/config_2
data/configs/waydroid.seccomp
tools/helpers/lxc.py

Hello everyone! I propose enabling a container-wide seccomp filter.
Seccomp is a Linux kernel system call access self-restriction feature. A process can load a seccomp filter to the kernel that will check the system calls and block unwanted ones (or terminate the process). I propose a deny list filter that blocks system calls related to loading kernel modules, rebooting the computer, changing system time, kernel key management facility and swap. Seccomp filter will block these syscalls, and the most dangerous ones will lead to termination of the process.
**Possible benefits**:
Mitigating the most dangerous security risks (such as kernel modification) for example, in case of vulnerabilities in root processes in the container.
**Possible problems**:
This will prevent the …

Add a container-wide seccomp filter

---

tools/actions/container_manager.py
tools/helpers/images.py

On waydroid upgrade waydroid_base.prop might change so we should
rewrite the mountable waydroid.prop file as well.
Do this in mount_rootfs so that:
* Every caller already benefits from this (initializer, upgrader...)
* We can set props based on rootfs contents

Rebuild waydroid.prop after live upgrade

---

Makefile

This drops a [build-time dependency on `coreutils` on Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/38006#note_260624) for example without changing anything functionally.
Before: `/usr/bin/waydroid: symbolic link to ../lib/waydroid/waydroid.py`
After: `/usr/bin/waydroid: symbolic link to /usr/lib/waydroid/waydroid.py`

Makefile: Install waydroid binary without relative symlink

---

tools/actions/initializer.py
tools/actions/upgrader.py
tools/config/__init__.py
tools/helpers/lxc.py

Precedence:
/etc/waydroid-extra/images
/usr/share/waydroid-extra/images

Configure multiple preinstalled images paths

---

data/configs/config_base

Hello everyone! I propose removing CAP_SYS_MODULE from the capability bounding set.
POSIX capabilities are a way for granular management of superuser privileges in GNU/Linux systems. They allow granting some superuser privileges to a non-root process and restricting superuser privileges for a root process. CAP_SYS_MODULE is a capability that allows a process to load and unload kernel modules. Removing it would prevent root processes from modifying the kernel.
**Possible benefits**:
Protect the kernel from compromised root processes and root apps.
**Possible problems**:
I don't see any -- kernel module loading is already blocked by a [container-wide seccomp filter](https://github.com/waydroid/waydroid/pull/505).

Remove CAP_SYS_MODULE from the capability bounding set

---

data/configs/config_base

Hello everyone! I propose mounting the /proc directory inside the container with **hidepid=2** option.
The **hidepid** option of the **proc** filesystem restricts access to information about process status. It takes one of the [three possible values](https://man7.org/linux/man-pages/man5/proc.5.html):
* **0**-- no restriction, any process can access information about any other process
* **1** -- an unprivileged user can only access information about their own processes -- only root and users from the group passed as **gid** option of **proc** filesystem mounting can see information about other users' processes
* **2** -- like **1**, but the directories of the processes that can't be read by the user, are now hidden from them.
**Possible benefits**:
* Restrict the app's …

Mount proc with the hidepid=2 option

---

tools/config/__init__.py
tools/services/hardware_manager.py

This allows to use persist.waydroid.suspend as a way to automatically stop the session after an inactivity timeout, as opposed to merely freezing the container. Freeze still remains the default action.
To use it this way, add to waydroid.cfg:
```
suspend_action = stop
```

hardware-manager: Optionally stop the session on suspend

---

data/Waydroid.desktop
tools/services/user_manager.py

This allows environments like Phosh to consider Waydroid launchers as mobile-compatible, so they get displayed in default app list when undocked.

desktop: Mark as compatible with mobile form factor

---

data/scripts/waydroid-net.sh

The "default to `waydroid0`" was broken as `awk` never returned a non-zero exit code if the file exists but no match was found.
Also account for the key being named `lxc.network.link` on older LXC versions so one still has the ability to have a flexible Waydroid network configuration.
Cc: @aleasto @Quackdoc

net: Fix vnic name selection for LXC <=2

---

tools/helpers/arguments.py
tools/helpers/lxc.py

Hello! :wave:
Before:
```console
$ waydroid shell --help
usage: waydroid shell [-h] [COMMAND]
positional arguments:
COMMAND     command to run
options:
-h, --help  show this help message and exit
$ waydroid shell pm disable com.android.inputmethod.latin
usage: waydroid [-h] [-V] [-l LOG] [--details-to-stdout] [-v] [-q] [-w] {status,log,init,upgrade,session,container,app,prop,show-full-ui,first-launch,shell,logcat} ...
waydroid: error: unrecognized arguments: disable com.android.inputmethod.latin
```
After:
```console
$ waydroid shell --help
usage: waydroid shell [-h] [COMMAND ...]
positional arguments:
COMMAND     command to run
options:
-h, --help  show this help message and exit
$ waydroid shell pm disable com.android.inputmethod.latin
Package com.android.inputmethod.latin new state: …
```

fix(shell): allow command to have arguments

---

tools/actions/session_manager.py

`XDG_SESSION_TYPE` isn't a reliable check for Wayland being present (e.g. on Ubuntu Touch currently `XDG_SESSION_TYPE` is `mir` with `WAYLAND_DISPLAY` set to `wayland-0` as it also provides Wayland windowing.
Also mention the behavior of defaulting `WAYLAND_DISPLAY` to `wayland-0` in case it's not set.

session: warn about unset WAYLAND_DISPLAY instead of XDG_SESSION_TYPE

---

tools/actions/prop.py

There is a small typo that misses `tools.` when calling `helpers`, which has issues with setting props.

Fix prop set command

---

tools/actions/initializer.py
tools/config/__init__.py
tools/helpers/images.py
tools/helpers/mount.py

This allows the user to make modifications to the images that may persist between image upgrades.
For both the system and vendor image there's a set of two overlays:
- one, specified in config as "overlay", is a read-only persistent overlay meant for stuff like installing privileged apps that should persist between updates
- second one, specified as "overlay_rw", is a read-write overlay that stores the changes made by the user when they remount the mount point in read-write mode. This one is cleaned up when performing image upgrade to not carry potentially incompatible changes on between images

Mount overlays on top of image mount points

---

debian/waydroid.postinst
tools/actions/session_manager.py
tools/helpers/props.py

Enough with not checking we actually have a Wayland compositor around at all: start requiring the `WAYLAND_DISPLAY` socket actually exists as an absolute path or relatively under `XDG_RUNTIME_DIR`.
Additionally if `WAYLAND_DISPLAY` isn't an absolute path to the socket (most setups) ensure `XDG_RUNTIME_DIR` is set and error with a typically appropriate message.
Fixes https://github.com/waydroid/waydroid/issues/693, closes https://github.com/waydroid/waydroid/pull/246.
Also contains a few small irrelevant commits that shouldn't change runtime in any way.
Few questions though (@aleasto):
1. Should we support `WAYLAND_SOCKET` right now? [technically it's a part of the spec](https://wayland.freedesktop.org/docs/html/apb.html#Client-classwl__display_1af048371dfef7577bd39a3c04b78d0374) so I left …

session: Add strict WAYLAND_DISPLAY validity checks

---

tools/actions/initializer.py
tools/actions/upgrader.py
tools/helpers/lxc.py

This hasn't existed in mainline Linux kernels [since v5.18](https://cateee.net/lkddb/web-lkddb/ASHMEM.html) and trying to always mount it regardless just adds to the noise in `waydroid log` in most cases, so simply don't add it to `config_nodes` unless it actually exists.
Silences the following:
```
lxc-start: waydroid: ../src/lxc/utils.c: safe_mount: 1221 No such file or directory - Failed to mount "/dev/ashmem" onto "/usr/lib/lxc/rootfs/dev/ashmem"
```

lxc: Only add /dev/ashmem to config_nodes when it exists

---

tools/actions/container_manager.py

Failing the network setup will in 99% of all cases cause the `lxc-start` to fail due to the `waydroid0` bridge not existing, so we might as well fail fast instead of polluting the `waydroid log` and doing a futile attempt at booting the LXC container.
Fixes https://github.com/waydroid/waydroid/issues/694.
<details>
<summary>Click to show/hide logs BEFORE this patch with failing "waydroid-net.sh start"</summary>
```
$ waydroid show-full-ui
[20:51:18] Starting waydroid session
[20:51:29] OSError: container failed to start
(030513) [20:51:18] Starting waydroid session
(030516) [20:51:19] % modprobe -q ashmem_linux
(030516) [20:51:19] % chmod 666 -R /dev/anbox-binder
(030516) [20:51:19] % chmod 666 -R /dev/anbox-vndbinder
(030516) [20:51:19] % chmod 666 -R /dev/anbox-hwbinder
(030516) …
```

container: Make "waydroid-net.sh start" failure fatal

---

data/scripts/waydroid-net.sh

After 85843da (`container: Make "waydroid-net.sh start" failure fatal`) this could result always failing to start unless you ran `waydroid-net.sh stop` manually first; perhaps this should always be stopped upon encountering errors?

net: Don't fail start when already running

---

tools/helpers/version.py

Looks like the import was just forgotten in c0f595e.

version: Fix "NameError: name 're' is not defined"

---

tools/actions/container_manager.py

Toggling NFC on Ubuntu Touch 20.04 System Settings while Waydroid is running breaks NFC for apps currently until another session is started.

container: Extend nfcd stop/start hacks to systemd

---

tools/helpers/images.py

These will take up quite a bit of space over time in `~/.local/share/waydroid/data/lineageos_updates/` and should be cleaned up during the update process.

images: Cleanup Waydroid Updater zips after extracting

---

Makefile
data/Waydroid.desktop
tools/services/user_manager.py

This PR installs the 512x512 Waydroid icon into the standard Freedesktop.org `hicolor` fallback icon theme. This enables the use of icon names in the `.desktop` file, as exhibited in a commit inside this PR.
In addition, the location of the icon has been moved into a more organized place. Changes necessary to keep the app from breaking has been done.

Install icons to hicolor

---

tools/helpers/arch.py

Typically `armv8l` should catch these, but it seems some Android downstream kernels at least cheat and don't report the correct thing.

arch: Fallback to arm on weird arm64 kernels with 32-bit userspace

---

data/waydroid.app.install.desktop
data/waydroid.market.desktop
tools/actions/initializer.py

Since 574405d it's additionally installed under a 512x512 XDG icon dir just looking it up by `waydroid` should work.
@aleasto Please confirm the `first-launch` GTK3 window icon works properly ideally under both KDE and GNOME; my typical test compositor `weston` has no window icons to speak of :)

Fix last hardcoded direct usages of AppIcon.png

---

tools/services/user_manager.py

This pull request adds an option to open the App's Settings page to easily manage the app's permissions or to uninstall the app, similar to GNOMES "Show Details"
Closes #805

Add App Settings to .desktop file

---

data/Waydroid.desktop
tools/services/user_manager.py

This pull request adds the 'X-WayDroid-App' category to the WayDroid desktop file and those for apps installed inside WayDroid, to allow for them to be grouped by the desktop environment.

Add X-WayDroid-App category to auto-generated WayDroid desktop files

---

data/configs/apparmor_profiles/adbd
data/configs/apparmor_profiles/android_app
data/configs/apparmor_profiles/lxc-waydroid

Hello everyone!
During the last year, [a commit has been merged](https://github.com/waydroid/waydroid/pull/506) that enables AppArmor for the container. In order to avoid breaking any existing installations and work out policy mistakes, all profiles have been switched into the *complain* mode, in which AppArmor handles domain transitions, logs violations, but doesn't enforce rules (except for deny rules). If proposed AppArmor policies are somehow too restrictive for a container to work properly, it will show up in the audit log.
If you have AppArmor enabled on your system, you can help with AppArmor support in Waydroid:
* by reporting any policy violations by Android container processes in the audit log on your system (/var/log/audit/audit.log if auditd is installed and system log if it's …

Switch AppArmor profiles for the Waydroid container into "enforce" mode

---

tools/services/user_manager.py

waydroid create .desktop files in a user's ~/.local/share/applications folder with chmod 755 permissions. They should be 644. The permissions are properly set for the desktop file in /usr/share/applications

.desktop files should not be executable

---

tools/actions/status.py
tools/helpers/net.py
tools/services/user_manager.py

To make my workflow during android development easier, I implemented
- a display of Waydroid's local IP address to the status command
- an automatic call to ADB connect (if available on the host system) once the system is ready
The IP address is taken from the DHCP lease file for the default network configuration. Tested on cachyos with Waydroid installed from the AUR.
As I am not very familiar with Python or with the code structure, any feedback is very appreciated. Please let me know if this fits the project or if changes are necessary for issues or use cases that I didn't think of.
Possible alternatives:
- Just displaying the IP address in the status
- Adding a subcommand, such as `waydroid adb connect` instead of automatically connecting
Some related issues: #164 #845

Add device IP address to status, auto adb connect

---

tools/__init__.py
tools/helpers/arguments.py
tools/helpers/lxc.py

In this pull request, I propose a new subcommand, ```waydroid custom-shell```, that runs a shell command in the Android container as an arbitrary user, not just as root. It works in a way similar to ```waydroid shell```, by running ```lxc-launch```, but passes more command-line arguments to it. Currently, we have the ```waydroid shell``` subcommand that allows running a command inside the Android container as root. However, unlike the vast majority of other Linux distributions, Android doesn't have any utility similar to ```su``` or ```doas```, which makes running a command as an arbitrary user harder (and not all commands have to be run with the most privileged security context. In this PR, I add another subcommand that accepts more command-line arguments that alllow the user to set UID, …

Allow running a shell command as an arbitrary user and group and with an arbitrary security context

---

tools/services/clipboard_manager.py

Repeatedly, people have understood the current warning as indication of the actual problem they experience (#83, #117, #276…) so make it more informative & a little less dramatic.

clipboard: change warning message to be less misleading

---

tools/actions/container_manager.py

Certain devices with Ubuntu Touch make use of the schedtune cgroup boosting mechanism, allowing for better performance system-wide with very little tweaking. Some devices have trouble using this cgroup in a regular GNU/Linux setting because their kernels are not carrying the necessary kernel patch for enabling nesting [here].
To please both those that want Waydroid to stop dropping their performance as well as those having unpatched kernels, probe the capability to nest schedtune cgroups before deciding to unmount it.
[here]: https://gitlab.com/ubports/porting/reference-device-ports/android9/google-pixel-3a/android_kernel_google_bonito/-/commit/6452429d1f1dbdc9e1e310e82cc18664f2d1b56d

container_manager: Keep schedtune cgroup around in case nesting is supported

---

Makefile
data/configs/apparmor_profiles/adbd
data/configs/apparmor_profiles/android_app
data/configs/apparmor_profiles/lxc-waydroid

Hello everyone! I propose adding an include to three AppArmor profiles currently supplied by the Waydroid project, in order to allow users to make their own amendments to the AppArmor policy. The reason for this is, when these changes are made in the main policy files, these changes can conflict with new versions of profiles during upgrades, and in some cases, get overwritten. In order to avoid this, we can store the Waydroid-supplied policy and user's changes separately, and update only Waydroid-supplied files.

Allow local amendments to the AppArmor policy

---

tools/services/user_manager.py

chmod(0o644) is no longer necessary after umask(0) removal in da4772c4e54467920d642e2a792c5d16d3b7bf33 ("tools: Remove umask 0") as the default umask is 0o022, but if the umask is stricter (e.g. 0o027), then the user would expect the created files to be 0o640. Creating the directory with the correct mode already also avoids potential race conditions on systems with insufficient umask. ~~Also, by reversing the logic to the intended flow, it avoids issues mentioned in #817.~~
While at it, also use templating strings for .desktop file creation to simplify the logic and split the template from the actual code a bit.

user_manager: Respect user umask and use less code

---

data/configs/waydroid.seccomp

Hello everyone! I propose blocking the ```open_by_handle_at``` system call container-wide.
Seccomp is a Linux kernel system call access self-restriction feature. A process can load a seccomp filter to the kernel that will check the system calls and block unwanted ones (or terminate the process).
```open_by_handle_at``` is a system call that allows a privileged process (for which ```CAP_DAC_READ_SEARCH``` is effective) to open a file referring it by a byte array known as file handle. The file handle can be obtained by any process using the ```name_to_handle_at``` system call. The reason why ```open_by_handle_at``` is dangerous is that a container may have some file systems mounted it with limited visibility using a bind mount (by which I mean, that a subdirectory of a file …

Block the "open_by_handle_at" system call (part of anti-escape protection for rooted containers)

---

tools/helpers/net.py

Python interprets \d as invalid escape sequence.  In a future Python version there will be a SyntaxWarning and eventually a SyntaxError.
Fix this via declaring the RegEx pattern as a raw string instead by prepending r

update regex for deprecation warning

---

tools/helpers/arch.py

This patch adds a simple SSSE3 check for x86/x86_64 targets to provide log info and prevent container from simply crashing.
Fixes: (some) waydroid container/session "_fails to start_" issues
Greetings,
Waydroid installed on my CPU, initialized and downloaded images, but failed to start.
Only clue provided in waydroid.log was:
`lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126`
_(many unresolved issues present a similar line in their logs...)_
Debugging indicated it was actually crashing on an illegal instruction: `pshufb`.
...so it turns out **my CPU does not support SSSE3**.
related: [issue #617](https://github.com/waydroid/waydroid/issues/617#issuecomment-1725791124)
Yes, it's documented that `SSSE3` is required for all x86/x86_64 CPUs now:
[Android …

Add SSSE3 CPU check for arch x86/x86_64

---

Makefile

As per #1218 allow the installation of files relative to `/etc` to be specified through the command-line.
This patch uses sysconfdir as defined at https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

Add sysconfdir to Makefile defaulting to /etc

---

tools/services/user_manager.py

This PR is a proposal to solve PR https://github.com/waydroid/waydroid/pull/817.
- On usual installations, it won't change a thing to current behaviour.
- On installations where a user may want to preserve their changes to the `Waydroid.desktop` file, they now can by setting it as read-only (`chmod -r`, Windows readonly attribute, etc.).

Don't change user-defined desktop files for Waydroid when they're set as read-only

---

tools/actions/initializer.py

API 32 (12L) vendor was getting detected as `HALIUM_13` which wouldn't work on devices when official images ship with support for these newer versions.

initializer: Fix Halium version VNDK detection logic for 12L+

---

tools/helpers/gpu.py

I am using a chromebook (trogdor model) which uses a Qualcomm turnip gpu. The driver name should be "msm_dpu" on my machine.

Add msm_dpu driver for freedreno

---

tools/config/__init__.py
tools/helpers/images.py
tools/helpers/lxc.py

Mount XDG_RUNTIME_DIR, PULSE_RUNTIME_PATH and
WAYLAND_DISPLAY to our own synthetic paths in
/waydroid/xdg/...
That way, they can never clash with any of our
Android bindpoints.
Eg. /data/.../xdg/wayland-0 conflicts with /data

Use synthetic paths for host sockets

---

tools/helpers/gpu.py

In some kernels the i915_capabilities file is not present for the render node, but it is for the card node.

gpu: Check i915_capabilities for the card node

---

README.md

Previously, the link to file a bug report in the `README` pointed to `/issues/new`, but it is probably better for it to point to `/issues/new/choose`. This should encourage people to use the issue templates.

Fix bug report link

---

tools/helpers/lxc.py

Hello everyone! I propose enabling the ```ro.adb.secure``` property.
Android Debug Bridge is a tools that allows remote communication with the Android system. On the Android system side, it's represented by the Android Debug Bridge Daemon, that runs as a special user (```shell```). ```ro.adb.secure``` is a property that allows ADBD to be managed by Android settings. If ```ro.adb.secure``` is set to ```0```, anyone that can connect to the Android system over network (including installed Android apps connecting to ```127.0.0.1```) can get access to the privileged shell with lots of irrevocable Android permissions, and remotely control the system through tools like ```scrcpy```. If it's set to ```1```, all such interactions have to be authorized by the user -- it cannot be …

Enable the "ro.adb.secure" property
